project:
  type: website

website:
  title: "DSAN-5000: Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: clustering/clustering.qmd
        text: Clustering
      - href: eda/eda.ipynb
        text: Data Exploration
format:
  html:
    theme: cosmo
    toc: true



