project:
  type: website

website:
  title: "DSAN-5000: Project"
  reader-mode: true
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: https://github.com/mfgeary
        text: Code
      - text: Data
        menu:
          - text: Raw Data
          menu:
            - text: Reddit r/Psychosis
              href: data/reddit_psychosis_data.json
            - text: Reddit r/Schizophrenia
              href: data/reddit_schizophrenia_data.json
            - text: Reddit r/Cannabis
              href: data/reddit_cannabis_data.json
            - text: Wikipedia Data
              href: https://github.com/anly501/dsan-5000-project-mfgeary/tree/main/dsan-website/5000-website
          - text: Clean Data
          menu:
            - text:
      - href: introduction/introduction.qmd
        text: Introduction
      - href: data-collection.qmd
        text: Data Gathering
      - href: data-cleaning.qmd
        text: Data Cleaning
      - href: eda/eda.ipynb
        text: Data Exploration
      - href: work-in-progress.qmd
        text: Clustering
      - href: work-in-progress.qmd
        text: Dimensionality Reduction
      - text: Decision Trees
        menu:
        - text: Classification
          href: work-in-progress.qmd
        - text: Regression
          href: work-in-progress.qmd
      - text: ARM
        href: work-in-progress.qmd
      - text: Conclusions
        href: work-in-progress.qmd
    collapse-below: xxl
  page-footer: 
    left: "Authored by Marion Geary Bauman, 2023"
    right:
      - icon: github
        href: https://github.com/mfgeary
      - icon: linkedin
        href: https://www.linkedin.com/in/marion-geary

format:
  html:
    theme: flatly
    toc: true