<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regression with Decision Trees</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../style.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">DSAN 5000: Cannabis and Psychosis</span>
    </a>
  </div>
          <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://mgb.georgetown.domains" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
</ul>
          <div class="quarto-navbar-tools ms-auto">
    <a href="https://github.com/mfgeary" rel="" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
    <a href="https://www.linkedin.com/in/marion-geary-bauman" rel="" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-linkedin"></i></a>
</div>
            <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../decision-tree/classification/classification.html">Decision Trees</a></li><li class="breadcrumb-item"><a href="../../decision-tree/regression/regression.html">Regression</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About Marion</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://github.com/anly501/dsan-5000-project-mfgeary" class="sidebar-item-text sidebar-link"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text">Code</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://github.com/anly501/dsan-5000-project-mfgeary/tree/main/dsan-website/5000-website/data/raw_data" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Raw Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://github.com/anly501/dsan-5000-project-mfgeary/tree/main/dsan-website/5000-website/data" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Clean Data</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../introduction/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../data-collection/data-collection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Gathering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../data-cleaning/data-cleaning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Cleaning</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../eda/eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Exploration</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../naive-bayes/naive-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Naïve Bayes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../clustering/clustering.ipynb" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Clustering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../dim-reduction/dim-reduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dimensionality Reduction</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Decision Trees</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../decision-tree/classification/classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Classification</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../decision-tree/regression/regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../sentiment_analysis/sentiment_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sentiment Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../conclusions/conclusions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conclusions</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a>
  <ul class="collapse">
  <li><a href="#decision-tree" id="toc-decision-tree" class="nav-link" data-scroll-target="#decision-tree">Decision Tree</a></li>
  <li><a href="#random-forest" id="toc-random-forest" class="nav-link" data-scroll-target="#random-forest">Random Forest</a></li>
  </ul></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#implementation" id="toc-implementation" class="nav-link" data-scroll-target="#implementation">Implementation</a>
  <ul class="collapse">
  <li><a href="#baseline-model" id="toc-baseline-model" class="nav-link" data-scroll-target="#baseline-model">Baseline Model</a></li>
  <li><a href="#decision-tree-1" id="toc-decision-tree-1" class="nav-link" data-scroll-target="#decision-tree-1">Decision Tree</a></li>
  <li><a href="#random-forest-1" id="toc-random-forest-1" class="nav-link" data-scroll-target="#random-forest-1">Random Forest</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression with Decision Trees</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>As the next step of our analysis, we will be attempting to predict the <code>smipppy</code>, (Predicted Probability of Severe Mental Illness in the Past Year) using the NSDUH data. Our goal is to use data on cannabis use to predict the probability of severe mental illness.</p>
<p>In order to do this prediction task, we will use decision tree. First, we will use a simple decision tree as a baseline model for comparison. Next, we will use stochastic gradient boosting to improve the performance of our model. Finally, we will use a random forest model to see if we can improve our model further.</p>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<p>Before we begin the implementation of our models, we will give a brief technical overview of the methods we will be using.</p>
<section id="decision-tree" class="level3">
<h3 class="anchored" data-anchor-id="decision-tree">Decision Tree</h3>
<p>A decision tree is a simple method for both classification and regression. Decision trees are non-parametric models that are very easy to implement, understand, and visualize. Decision tress are often chosen for their high interpretability, since they are easy to understand and provide transparency into how the model makes predictions.</p>
<p>Decision trees work by developing a sequential set of rules that are used to predict the target variable. For a numeric feature, a decision tree starts by looking at all the data and finding the optimal feature and split point to minimize the sum of squared errors. This means the data will be split into observations where the given feature value is less than the split point and observations where the given feature value is more than the split point. For a categorical feature, the decision tree will split the data into observations based on the categories of the feature, again using the sum of squared errors to find a split point. This process is repeated recursively, continually subdividing the nodes, until a stopping point is reached. When the stopping point is met, each leaf node will represent a numeric value derived as the average of the target variable for all the observations in that leaf node.</p>
<p>When implementing a decision tree, there are a few hyperparameters that can be tuned for better performance. The maximum depth of the tree can be tuned to find the optimal number of splits. The minimum number of samples required to split an internal node can also be tuned, preventing the tree from splitting nodes with too few observations. The metric used to measure the quality of a split can also be tuned, but we will use the default metric which is the sum of squared errors.</p>
<p>While fitting a single decision tree to the data is easy, fast, and highly interpretable, it has significant drawbacks. Decision trees are prone to overfitting, especially without tuning the hyperparameters or pruning. Decision trees are also unstable, meaning that small changes in the data can lead to large changes how the model is built and makes predictions. Decision trees also make highly local predictions since they work much like a large piecewise function, meaning they cannot extrapolate well to new data.</p>
</section>
<section id="random-forest" class="level3">
<h3 class="anchored" data-anchor-id="random-forest">Random Forest</h3>
<p>Random forest is an ensemble method that combines multiple decision trees into one model that performs better than an individual tree. Random forests are effective at combatting the weaknesses of single decision trees. They tend to have better performance and are less prone to overfitting. They are also more stable because predictions come from an ensemble of trees rather than one single tree.</p>
<p>Random forest work by first creating a data set sample from the original data set, with replacement. This new bootstrapped data set is the same size as the initial data set. Next, a decision tree is fit to the bootstrapped data set. However, at each node, a random subset of features is selected. Then, the tree is built in te same way as the normal decision tree, finding an optimal split point and minimizing the sum of squared errors. This process is repeated for many trees, each turning out different due to the bootstrapping and random feature selection. Finally, the predictions from each tree are averaged to get the final prediction, creating an ensemble learner.</p>
<p>When implementing a random forest, there are hyperparameters that can be tuned to improve performance. The number of predictors chosen at each split can be tuned. Typically, the best number is the square root of the total number of predictors. The same hyperparameters as the decision tree can also be tuned, such as the maximum depth of the tree and the minimum number of samples required to split an internal node.</p>
</section>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>Once again, we will be use the NSDUH data set from SAMSHA to employ substance usage data to predict mental health outcomes. Our target variable will be <code>smipppy</code>, which is the predicted probability of severe mental illness in the past year. Our predictor variables will be variables relating to cannabis usage.</p>
<div class="cell" data-execution_count="119">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> pd.read_csv(<span class="st">'../../../data/clean_data/nsduh_2021.csv'</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh[[<span class="st">'mjage'</span>, <span class="st">'mjmfu'</span>, <span class="st">'mjyrtot'</span>, <span class="st">'mrbstway'</span>, <span class="st">'mrdaypyr'</span>, <span class="st">'mrdaypwk'</span>, <span class="st">'MR30EST'</span>, <span class="st">'smipppy'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="120">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace all values equal to 999 with NaN</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">9991</span>, <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">991</span>, <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">91</span>, <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">9993</span>, <span class="op">-</span><span class="dv">2</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">993</span>, <span class="op">-</span><span class="dv">2</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">93</span>, <span class="op">-</span><span class="dv">2</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">9994</span>, np.nan)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">994</span>, np.nan)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">94</span>, np.nan)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">9997</span>, np.nan)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">997</span>, np.nan)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">97</span>, np.nan)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">9998</span>, np.nan)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">998</span>, np.nan)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">98</span>, np.nan)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">9999</span>, np.nan)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">999</span>, np.nan)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">99</span>, np.nan)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">9981</span>, <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">981</span>, <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">81</span>, <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">9983</span>, <span class="op">-</span><span class="dv">2</span>)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">983</span>, <span class="op">-</span><span class="dv">2</span>)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">83</span>, <span class="op">-</span><span class="dv">2</span>)</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">9985</span>, np.nan)</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">985</span>, np.nan)</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">85</span>, np.nan)</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">9989</span>, np.nan)</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">989</span>, np.nan)</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="dv">89</span>, np.nan)</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'9991'</span>, <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'991'</span>, <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'91'</span>, <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'9993'</span>, <span class="op">-</span><span class="dv">2</span>)</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'993'</span>, <span class="op">-</span><span class="dv">2</span>)</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'93'</span>, <span class="op">-</span><span class="dv">2</span>)</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'9994'</span>, np.nan)</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'994'</span>, np.nan)</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'94'</span>, np.nan)</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'9997'</span>, np.nan)</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'997'</span>, np.nan)</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'97'</span>, np.nan)</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'9998'</span>, np.nan)</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'998'</span>, np.nan)</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'98'</span>, np.nan)</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'9999'</span>, np.nan)</span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'999'</span>, np.nan)</span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'99'</span>, np.nan)</span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'9981'</span>, <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'981'</span>, <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'81'</span>, <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'9983'</span>, <span class="op">-</span><span class="dv">2</span>)</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'983'</span>, <span class="op">-</span><span class="dv">2</span>)</span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'83'</span>, <span class="op">-</span><span class="dv">2</span>)</span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'9985'</span>, np.nan)</span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'985'</span>, np.nan)</span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'85'</span>, np.nan)</span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'9989'</span>, np.nan)</span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'989'</span>, np.nan)</span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'89'</span>, np.nan)</span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.replace(<span class="st">'Never Used'</span>, <span class="op">-</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="122">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># combine mrdaypyr and mrdaypwk into one column</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>nsduh[<span class="st">'mrdaypyr'</span>] <span class="op">=</span> nsduh[<span class="st">'mrdaypyr'</span>].fillna(<span class="dv">0</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>nsduh[<span class="st">'mrdaypwk'</span>] <span class="op">=</span> nsduh[<span class="st">'mrdaypwk'</span>].fillna(<span class="dv">0</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># if value is positive, multiply by 52 to get yearly value</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>nsduh[<span class="st">'days_per_year'</span>] <span class="op">=</span> nsduh[<span class="st">'mrdaypwk'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="bu">int</span>(x) <span class="op">*</span> <span class="dv">52</span> <span class="cf">if</span> <span class="bu">int</span>(x) <span class="op">&gt;</span> <span class="dv">0</span> <span class="cf">else</span> x)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># mutate mrdaypyr and mrdaypwk to be numeric</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>nsduh[<span class="st">'mrdaypyr'</span>] <span class="op">=</span> pd.to_numeric(nsduh[<span class="st">'mrdaypyr'</span>], errors<span class="op">=</span><span class="st">'coerce'</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>nsduh[<span class="st">'mrdaypwk'</span>] <span class="op">=</span> pd.to_numeric(nsduh[<span class="st">'mrdaypwk'</span>], errors<span class="op">=</span><span class="st">'coerce'</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>nsduh[<span class="st">'MR30EST'</span>] <span class="op">=</span> pd.to_numeric(nsduh[<span class="st">'MR30EST'</span>], errors<span class="op">=</span><span class="st">'coerce'</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co"># if mrdaypyr is positive, add to days_per_year</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>nsduh[<span class="st">'days_per_year'</span>] <span class="op">=</span> np.where(nsduh[<span class="st">'mrdaypyr'</span>] <span class="op">&gt;</span> <span class="dv">0</span>, nsduh[<span class="st">'days_per_year'</span>] <span class="op">+</span> nsduh[<span class="st">'mrdaypyr'</span>], nsduh[<span class="st">'days_per_year'</span>])</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>nsduh[<span class="st">'days_per_year'</span>] <span class="op">=</span> np.where(nsduh[<span class="st">'MR30EST'</span>] <span class="op">&gt;</span> <span class="dv">0</span>, nsduh[<span class="st">'MR30EST'</span>] <span class="op">*</span> <span class="dv">12</span>, nsduh[<span class="st">'days_per_year'</span>])</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.drop([<span class="st">'mrdaypyr'</span>, <span class="st">'mrdaypwk'</span>, <span class="st">'MR30EST'</span>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>nsduh</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="122">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">mjage</th>
<th data-quarto-table-cell-role="th">mjmfu</th>
<th data-quarto-table-cell-role="th">mjyrtot</th>
<th data-quarto-table-cell-role="th">mrbstway</th>
<th data-quarto-table-cell-role="th">smipppy</th>
<th data-quarto-table-cell-role="th">days_per_year</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>19</td>
<td>NaN</td>
<td>52</td>
<td>1</td>
<td>0.008998</td>
<td>52.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>-1</td>
<td>-1</td>
<td>-1</td>
<td>-1</td>
<td>0.008998</td>
<td>-1.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>-1</td>
<td>-1</td>
<td>-1</td>
<td>-1</td>
<td>0.028021</td>
<td>-1.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>13</td>
<td>NaN</td>
<td>364</td>
<td>1</td>
<td>0.071654</td>
<td>364.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>-1</td>
<td>-1</td>
<td>-1</td>
<td>-1</td>
<td>0.004786</td>
<td>-1.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">58029</td>
<td>21</td>
<td>NaN</td>
<td>-2</td>
<td>-2</td>
<td>0.008998</td>
<td>-2.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">58030</td>
<td>25</td>
<td>NaN</td>
<td>-2</td>
<td>-2</td>
<td>0.040617</td>
<td>-2.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">58031</td>
<td>18</td>
<td>NaN</td>
<td>48</td>
<td>2</td>
<td>0.003488</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">58032</td>
<td>19</td>
<td>NaN</td>
<td>3</td>
<td>3</td>
<td>0.008998</td>
<td>3.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">58033</td>
<td>-1</td>
<td>-1</td>
<td>-1</td>
<td>-1</td>
<td>0.003488</td>
<td>-1.0</td>
</tr>
</tbody>
</table>

<p>58034 rows × 6 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="123">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print type of each column</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(nsduh.dtypes)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># convert all columns to numeric</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.<span class="bu">apply</span>(pd.to_numeric)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>mjage             object
mjmfu             object
mjyrtot           object
mrbstway          object
smipppy          float64
days_per_year    float64
dtype: object</code></pre>
</div>
</div>
<div class="cell" data-execution_count="124">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>nsduh <span class="op">=</span> nsduh.dropna()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="149">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>nsduh.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="149">
<pre><code>(23969, 6)</code></pre>
</div>
</div>
</section>
<section id="implementation" class="level2">
<h2 class="anchored" data-anchor-id="implementation">Implementation</h2>
<p>Now that we have given a brief overview of the methods we will be using and loaded in our data, we can begin implementing our models.</p>
<p>We’ll start by splitting our into training and testing sets. We will use 80% of the data for training and 20% for testing. We will also set a random seed so that our results are reproducible.</p>
<div class="cell" data-execution_count="170">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Split the data into training and test sets</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>train_features, test_features, train_labels, test_labels <span class="op">=</span> train_test_split(nsduh.drop([<span class="st">'smipppy'</span>], axis<span class="op">=</span><span class="dv">1</span>), nsduh[<span class="st">'smipppy'</span>], test_size<span class="op">=</span><span class="fl">0.20</span>, random_state<span class="op">=</span><span class="dv">371</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="baseline-model" class="level3">
<h3 class="anchored" data-anchor-id="baseline-model">Baseline Model</h3>
<p>Our baseline model will be entirely random numeric predictions. We will use the root mean squared error to evaluate the performance of our baseline model.</p>
<div class="cell" data-execution_count="151">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create random predictor which gives any value between 0 and 1</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> random</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>random.seed(<span class="dv">371</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>rand_pred <span class="op">=</span> [random.uniform(<span class="dv">0</span>, <span class="dv">1</span>) <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(test_labels))]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="152">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the random model</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_squared_error</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_absolute_error</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> r2_score</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>rand_mse <span class="op">=</span> mean_squared_error(test_labels, rand_pred)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>rand_rmse <span class="op">=</span> np.sqrt(rand_mse)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Random RMSE: '</span>, rand_rmse)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>rand_mae <span class="op">=</span> mean_absolute_error(test_labels, rand_pred)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Random MAE: '</span>, rand_mae)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>rand_r2 <span class="op">=</span> r2_score(test_labels, rand_pred)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Random R2: '</span>, rand_r2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Random RMSE:  0.5527905917092234
Random MAE:  0.47304614099131814
Random R2:  -19.30031772945689</code></pre>
</div>
</div>
</section>
<section id="decision-tree-1" class="level3">
<h3 class="anchored" data-anchor-id="decision-tree-1">Decision Tree</h3>
<p>Next, we will use a normal decision tree. We expect this model to perform only moderately well, but it will give us a reference to compare our more advanced models to. We will tune for the maximum depth of the tree and the minimum number of samples required to split an internal node.</p>
<div class="cell" data-execution_count="153">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.tree <span class="im">import</span> DecisionTreeRegressor</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.tree <span class="im">import</span> plot_tree</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Tune hyperparameters</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> {}</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> max_depth <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">5</span>, <span class="dv">15</span>):</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> min_samples_split <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">2</span>, <span class="dv">10</span>):</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>        decision_tree <span class="op">=</span> DecisionTreeRegressor(random_state<span class="op">=</span><span class="dv">371</span>, max_depth<span class="op">=</span>max_depth, min_samples_split<span class="op">=</span>min_samples_split)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>        decision_tree.fit(train_features, train_labels)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>        decision_tree_pred <span class="op">=</span> decision_tree.predict(test_features)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>        decision_tree_mse <span class="op">=</span> mean_squared_error(test_labels, decision_tree_pred)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>        decision_tree_rmse <span class="op">=</span> np.sqrt(decision_tree_mse)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>        decision_tree_mae <span class="op">=</span> mean_absolute_error(test_labels, decision_tree_pred)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>        decision_tree_r2 <span class="op">=</span> r2_score(test_labels, decision_tree_pred)</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>        results[(max_depth, min_samples_split)] <span class="op">=</span> decision_tree_rmse, decision_tree_mae, decision_tree_r2, decision_tree, decision_tree_pred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="172">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib <span class="im">import</span> pyplot <span class="im">as</span> plt</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>plt.scatter(train_features[<span class="st">'mjage'</span>], train_labels, c<span class="op">=</span><span class="st">'b'</span>, label<span class="op">=</span><span class="st">'Training'</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>plt.plot(test_features[<span class="st">'mjage'</span>], results[(<span class="dv">5</span>, <span class="dv">2</span>)][<span class="dv">4</span>], c<span class="op">=</span><span class="st">'r'</span>, label<span class="op">=</span><span class="st">'min_samples_split=2'</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>plt.plot(test_features[<span class="st">'mjage'</span>], results[(<span class="dv">5</span>, <span class="dv">4</span>)][<span class="dv">4</span>], c<span class="op">=</span><span class="st">'y'</span>, label<span class="op">=</span><span class="st">'min_samples_split=4'</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>plt.plot(test_features[<span class="st">'mjage'</span>], results[(<span class="dv">5</span>, <span class="dv">6</span>)][<span class="dv">4</span>], c<span class="op">=</span><span class="st">'m'</span>, label<span class="op">=</span><span class="st">'min_samples_split=6'</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>plt.plot(test_features[<span class="st">'mjage'</span>], results[(<span class="dv">5</span>, <span class="dv">8</span>)][<span class="dv">4</span>], c<span class="op">=</span><span class="st">'g'</span>, label<span class="op">=</span><span class="st">'min_samples_split=8'</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="regression_files/figure-html/cell-12-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="173">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>results_df <span class="op">=</span> pd.DataFrame(results).T.reset_index()</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>results_df.columns <span class="op">=</span> [<span class="st">'max_depth'</span>, <span class="st">'min_samples_split'</span>, <span class="st">'rmse'</span>, <span class="st">'mae'</span>, <span class="st">'r2'</span>, <span class="st">'model'</span>, <span class="st">'pred'</span>]</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>results_df.sort_values(<span class="st">'rmse'</span>, ascending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>best_max_depth <span class="op">=</span> results_df.sort_values(<span class="st">'rmse'</span>, ascending<span class="op">=</span><span class="va">True</span>).iloc[<span class="dv">0</span>][<span class="st">'max_depth'</span>]</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>best_max_depth <span class="op">=</span> <span class="bu">int</span>(best_max_depth)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>best_min_samples_split <span class="op">=</span> results_df.sort_values(<span class="st">'rmse'</span>, ascending<span class="op">=</span><span class="va">True</span>).iloc[<span class="dv">0</span>][<span class="st">'min_samples_split'</span>]</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>best_min_samples_split <span class="op">=</span> <span class="bu">int</span>(best_min_samples_split)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="159">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>decision_tree <span class="op">=</span> DecisionTreeRegressor(random_state<span class="op">=</span><span class="dv">371</span>, max_depth<span class="op">=</span>best_max_depth, min_samples_split<span class="op">=</span>best_min_samples_split)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>decision_tree.fit(train_features, train_labels)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>decision_tree_pred <span class="op">=</span> decision_tree.predict(test_features)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>decision_tree_mse <span class="op">=</span> mean_squared_error(test_labels, decision_tree_pred)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>decision_tree_rmse <span class="op">=</span> np.sqrt(decision_tree_mse)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Decision Tree RMSE: '</span>, decision_tree_rmse)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>decision_tree_mae <span class="op">=</span> mean_absolute_error(test_labels, decision_tree_pred)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Decision Tree MAE: '</span>, decision_tree_mae)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>decision_tree_r2 <span class="op">=</span> r2_score(test_labels, decision_tree_pred)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Decision Tree R2: '</span>, decision_tree_r2)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>plot_tree(decision_tree)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Decision Tree RMSE:  0.12205319291140562
Decision Tree MAE:  0.05658890114799911
Decision Tree R2:  0.01035407758738438</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="159">
<pre><code>[Text(0.46209016393442626, 0.9285714285714286, 'x[1] &lt;= 2.5\nsquared_error = 0.015\nsamples = 19175\nvalue = 0.043'),
 Text(0.20491803278688525, 0.7857142857142857, 'x[2] &lt;= 234.0\nsquared_error = 0.014\nsamples = 18610\nvalue = 0.041'),
 Text(0.1885245901639344, 0.6428571428571429, 'x[2] &lt;= 2.5\nsquared_error = 0.014\nsamples = 18605\nvalue = 0.041'),
 Text(0.09016393442622951, 0.5, 'x[2] &lt;= -1.5\nsquared_error = 0.014\nsamples = 18555\nvalue = 0.041'),
 Text(0.03278688524590164, 0.35714285714285715, 'x[0] &lt;= 18.5\nsquared_error = 0.0\nsamples = 16\nvalue = 0.012'),
 Text(0.01639344262295082, 0.21428571428571427, 'squared_error = 0.0\nsamples = 4\nvalue = 0.022'),
 Text(0.04918032786885246, 0.21428571428571427, 'x[1] &lt;= 1.5\nsquared_error = 0.0\nsamples = 12\nvalue = 0.009'),
 Text(0.03278688524590164, 0.07142857142857142, 'squared_error = 0.0\nsamples = 4\nvalue = 0.006'),
 Text(0.06557377049180328, 0.07142857142857142, 'squared_error = 0.0\nsamples = 8\nvalue = 0.01'),
 Text(0.14754098360655737, 0.35714285714285715, 'x[0] &lt;= 21.5\nsquared_error = 0.014\nsamples = 18539\nvalue = 0.041'),
 Text(0.11475409836065574, 0.21428571428571427, 'x[1] &lt;= 1.5\nsquared_error = 0.014\nsamples = 18526\nvalue = 0.041'),
 Text(0.09836065573770492, 0.07142857142857142, 'squared_error = 0.014\nsamples = 18522\nvalue = 0.041'),
 Text(0.13114754098360656, 0.07142857142857142, 'squared_error = 0.011\nsamples = 4\nvalue = 0.136'),
 Text(0.18032786885245902, 0.21428571428571427, 'x[0] &lt;= 32.5\nsquared_error = 0.001\nsamples = 13\nvalue = 0.023'),
 Text(0.16393442622950818, 0.07142857142857142, 'squared_error = 0.0\nsamples = 10\nvalue = 0.015'),
 Text(0.19672131147540983, 0.07142857142857142, 'squared_error = 0.003\nsamples = 3\nvalue = 0.05'),
 Text(0.28688524590163933, 0.5, 'x[0] &lt;= 19.5\nsquared_error = 0.026\nsamples = 50\nvalue = 0.081'),
 Text(0.22950819672131148, 0.35714285714285715, 'x[2] &lt;= 3.5\nsquared_error = 0.051\nsamples = 21\nvalue = 0.139'),
 Text(0.21311475409836064, 0.21428571428571427, 'squared_error = 0.094\nsamples = 3\nvalue = 0.455'),
 Text(0.2459016393442623, 0.21428571428571427, 'x[4] &lt;= 54.0\nsquared_error = 0.025\nsamples = 18\nvalue = 0.086'),
 Text(0.22950819672131148, 0.07142857142857142, 'squared_error = 0.013\nsamples = 15\nvalue = 0.064'),
 Text(0.26229508196721313, 0.07142857142857142, 'squared_error = 0.067\nsamples = 3\nvalue = 0.199'),
 Text(0.3442622950819672, 0.35714285714285715, 'x[4] &lt;= 3.5\nsquared_error = 0.004\nsamples = 29\nvalue = 0.038'),
 Text(0.3114754098360656, 0.21428571428571427, 'x[2] &lt;= 18.0\nsquared_error = 0.007\nsamples = 14\nvalue = 0.066'),
 Text(0.29508196721311475, 0.07142857142857142, 'squared_error = 0.003\nsamples = 11\nvalue = 0.048'),
 Text(0.32786885245901637, 0.07142857142857142, 'squared_error = 0.015\nsamples = 3\nvalue = 0.132'),
 Text(0.3770491803278688, 0.21428571428571427, 'x[0] &lt;= 44.0\nsquared_error = 0.0\nsamples = 15\nvalue = 0.013'),
 Text(0.36065573770491804, 0.07142857142857142, 'squared_error = 0.0\nsamples = 11\nvalue = 0.008'),
 Text(0.39344262295081966, 0.07142857142857142, 'squared_error = 0.001\nsamples = 4\nvalue = 0.026'),
 Text(0.22131147540983606, 0.6428571428571429, 'squared_error = 0.155\nsamples = 5\nvalue = 0.336'),
 Text(0.7192622950819673, 0.7857142857142857, 'x[4] &lt;= 5.5\nsquared_error = 0.043\nsamples = 565\nvalue = 0.111'),
 Text(0.5860655737704918, 0.6428571428571429, 'x[0] &lt;= 41.5\nsquared_error = 0.037\nsamples = 429\nvalue = 0.1'),
 Text(0.5163934426229508, 0.5, 'x[2] &lt;= 37.0\nsquared_error = 0.04\nsamples = 394\nvalue = 0.107'),
 Text(0.47540983606557374, 0.35714285714285715, 'x[2] &lt;= 2.5\nsquared_error = 0.037\nsamples = 366\nvalue = 0.101'),
 Text(0.4426229508196721, 0.21428571428571427, 'x[0] &lt;= 23.5\nsquared_error = 0.044\nsamples = 226\nvalue = 0.12'),
 Text(0.4262295081967213, 0.07142857142857142, 'squared_error = 0.039\nsamples = 157\nvalue = 0.109'),
 Text(0.45901639344262296, 0.07142857142857142, 'squared_error = 0.055\nsamples = 69\nvalue = 0.145'),
 Text(0.5081967213114754, 0.21428571428571427, 'x[0] &lt;= 22.5\nsquared_error = 0.023\nsamples = 140\nvalue = 0.072'),
 Text(0.4918032786885246, 0.07142857142857142, 'squared_error = 0.018\nsamples = 105\nvalue = 0.06'),
 Text(0.5245901639344263, 0.07142857142857142, 'squared_error = 0.037\nsamples = 35\nvalue = 0.108'),
 Text(0.5573770491803278, 0.35714285714285715, 'x[2] &lt;= 41.5\nsquared_error = 0.072\nsamples = 28\nvalue = 0.177'),
 Text(0.5409836065573771, 0.21428571428571427, 'squared_error = 0.02\nsamples = 3\nvalue = 0.528'),
 Text(0.5737704918032787, 0.21428571428571427, 'x[0] &lt;= 19.5\nsquared_error = 0.062\nsamples = 25\nvalue = 0.134'),
 Text(0.5573770491803278, 0.07142857142857142, 'squared_error = 0.087\nsamples = 16\nvalue = 0.189'),
 Text(0.5901639344262295, 0.07142857142857142, 'squared_error = 0.003\nsamples = 9\nvalue = 0.037'),
 Text(0.6557377049180327, 0.5, 'x[1] &lt;= 3.5\nsquared_error = 0.001\nsamples = 35\nvalue = 0.028'),
 Text(0.639344262295082, 0.35714285714285715, 'squared_error = 0.004\nsamples = 2\nvalue = 0.07'),
 Text(0.6721311475409836, 0.35714285714285715, 'x[2] &lt;= 1.5\nsquared_error = 0.001\nsamples = 33\nvalue = 0.026'),
 Text(0.639344262295082, 0.21428571428571427, 'x[1] &lt;= 10.5\nsquared_error = 0.002\nsamples = 17\nvalue = 0.034'),
 Text(0.6229508196721312, 0.07142857142857142, 'squared_error = 0.001\nsamples = 14\nvalue = 0.027'),
 Text(0.6557377049180327, 0.07142857142857142, 'squared_error = 0.006\nsamples = 3\nvalue = 0.066'),
 Text(0.7049180327868853, 0.21428571428571427, 'x[0] &lt;= 55.0\nsquared_error = 0.0\nsamples = 16\nvalue = 0.017'),
 Text(0.6885245901639344, 0.07142857142857142, 'squared_error = 0.0\nsamples = 12\nvalue = 0.019'),
 Text(0.7213114754098361, 0.07142857142857142, 'squared_error = 0.0\nsamples = 4\nvalue = 0.01'),
 Text(0.8524590163934426, 0.6428571428571429, 'x[0] &lt;= 18.5\nsquared_error = 0.059\nsamples = 136\nvalue = 0.146'),
 Text(0.7868852459016393, 0.5, 'x[0] &lt;= 17.5\nsquared_error = 0.02\nsamples = 40\nvalue = 0.055'),
 Text(0.7540983606557377, 0.35714285714285715, 'x[1] &lt;= 7.5\nsquared_error = 0.043\nsamples = 15\nvalue = 0.112'),
 Text(0.7377049180327869, 0.21428571428571427, 'squared_error = 0.002\nsamples = 7\nvalue = 0.035'),
 Text(0.7704918032786885, 0.21428571428571427, 'x[1] &lt;= 8.5\nsquared_error = 0.069\nsamples = 8\nvalue = 0.179'),
 Text(0.7540983606557377, 0.07142857142857142, 'squared_error = 0.003\nsamples = 2\nvalue = 0.627'),
 Text(0.7868852459016393, 0.07142857142857142, 'squared_error = 0.001\nsamples = 6\nvalue = 0.029'),
 Text(0.819672131147541, 0.35714285714285715, 'x[4] &lt;= 7.0\nsquared_error = 0.003\nsamples = 25\nvalue = 0.021'),
 Text(0.8032786885245902, 0.21428571428571427, 'squared_error = 0.02\nsamples = 2\nvalue = 0.144'),
 Text(0.8360655737704918, 0.21428571428571427, 'x[4] &lt;= 8.5\nsquared_error = 0.0\nsamples = 23\nvalue = 0.011'),
 Text(0.819672131147541, 0.07142857142857142, 'squared_error = 0.0\nsamples = 1\nvalue = 0.062'),
 Text(0.8524590163934426, 0.07142857142857142, 'squared_error = 0.0\nsamples = 22\nvalue = 0.008'),
 Text(0.9180327868852459, 0.5, 'x[4] &lt;= 6.5\nsquared_error = 0.071\nsamples = 96\nvalue = 0.184'),
 Text(0.9016393442622951, 0.35714285714285715, 'squared_error = 0.089\nsamples = 6\nvalue = 0.358'),
 Text(0.9344262295081968, 0.35714285714285715, 'x[0] &lt;= 40.5\nsquared_error = 0.067\nsamples = 90\nvalue = 0.172'),
 Text(0.9016393442622951, 0.21428571428571427, 'x[0] &lt;= 28.5\nsquared_error = 0.074\nsamples = 78\nvalue = 0.192'),
 Text(0.8852459016393442, 0.07142857142857142, 'squared_error = 0.055\nsamples = 64\nvalue = 0.168'),
 Text(0.9180327868852459, 0.07142857142857142, 'squared_error = 0.148\nsamples = 14\nvalue = 0.303'),
 Text(0.9672131147540983, 0.21428571428571427, 'x[0] &lt;= 66.5\nsquared_error = 0.002\nsamples = 12\nvalue = 0.044'),
 Text(0.9508196721311475, 0.07142857142857142, 'squared_error = 0.001\nsamples = 10\nvalue = 0.026'),
 Text(0.9836065573770492, 0.07142857142857142, 'squared_error = 0.0\nsamples = 2\nvalue = 0.133')]</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="regression_files/figure-html/cell-14-output-3.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="180">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>plt.plot(train_features[<span class="st">'mjage'</span>], decision_tree.predict(train_features), color<span class="op">=</span><span class="st">"b"</span>, label<span class="op">=</span><span class="st">"training tree"</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>plt.scatter(train_features[<span class="st">'mjage'</span>], train_labels, c<span class="op">=</span><span class="st">'k'</span>, label<span class="op">=</span><span class="st">'training'</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>plt.scatter(test_features[<span class="st">'mjage'</span>], test_labels, c<span class="op">=</span><span class="st">'g'</span>, label<span class="op">=</span><span class="st">'testing'</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>plt.plot(test_features[<span class="st">'mjage'</span>], decision_tree_pred, c<span class="op">=</span><span class="st">'r'</span>, label<span class="op">=</span><span class="st">'final tree'</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="regression_files/figure-html/cell-15-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="random-forest-1" class="level3">
<h3 class="anchored" data-anchor-id="random-forest-1">Random Forest</h3>
<p>Finally, we will use a random forest model. We expect this model to perform better than our decision tree model.</p>
<div class="cell" data-execution_count="138">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestRegressor</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tqdm <span class="im">import</span> tqdm</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Tune hyperparameters</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>results_rf <span class="op">=</span> {}</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> n_estimators <span class="kw">in</span> tqdm(<span class="bu">range</span>(<span class="dv">100</span>, <span class="dv">1000</span>, <span class="dv">100</span>)):</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> max_depth <span class="kw">in</span> tqdm(<span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">15</span>)):</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>        random_forest <span class="op">=</span> RandomForestRegressor(random_state<span class="op">=</span><span class="dv">371</span>, n_estimators<span class="op">=</span>n_estimators, max_depth<span class="op">=</span>max_depth)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>        random_forest.fit(train_features, train_labels)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>        random_forest_pred <span class="op">=</span> random_forest.predict(test_features)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>        random_forest_mse <span class="op">=</span> mean_squared_error(test_labels, random_forest_pred)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>        random_forest_rmse <span class="op">=</span> np.sqrt(random_forest_mse)</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>        random_forest_mae <span class="op">=</span> mean_absolute_error(test_labels, random_forest_pred)</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>        random_forest_r2 <span class="op">=</span> r2_score(test_labels, random_forest_pred)</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>        results_rf[(n_estimators, max_depth, min_samples_split)] <span class="op">=</span> random_forest_rmse, random_forest_mae, random_forest_r2, random_forest, random_forest_pred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>  0%|          | 0/9 [00:00&lt;?, ?it/s]
  0%|          | 0/14 [00:00&lt;?, ?it/s]100%|██████████| 14/14 [00:05&lt;00:00,  2.70it/s]
100%|██████████| 14/14 [00:10&lt;00:00,  1.32it/s]
100%|██████████| 14/14 [00:16&lt;00:00,  1.17s/it]
100%|██████████| 14/14 [00:21&lt;00:00,  1.56s/it]
100%|██████████| 14/14 [00:26&lt;00:00,  1.92s/it]
100%|██████████| 14/14 [00:32&lt;00:00,  2.33s/it]
100%|██████████| 14/14 [00:37&lt;00:00,  2.69s/it]
100%|██████████| 14/14 [00:42&lt;00:00,  3.06s/it]
100%|██████████| 14/14 [00:47&lt;00:00,  3.38s/it]
100%|██████████| 9/9 [04:01&lt;00:00, 26.81s/it]</code></pre>
</div>
</div>
<div class="cell" data-execution_count="140">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>results_rf_df <span class="op">=</span> pd.DataFrame(results_rf).T.reset_index()</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>results_rf_df.columns <span class="op">=</span> [<span class="st">'n_estimators'</span>, <span class="st">'max_depth'</span>, <span class="st">'min_samples_split'</span>, <span class="st">'rmse'</span>, <span class="st">'mae'</span>, <span class="st">'r2'</span>, <span class="st">'model'</span>, <span class="st">'pred'</span>]</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>results_rf_df.sort_values(<span class="st">'rmse'</span>, ascending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>best_n_estimators <span class="op">=</span> results_rf_df.sort_values(<span class="st">'rmse'</span>, ascending<span class="op">=</span><span class="va">True</span>).iloc[<span class="dv">0</span>][<span class="st">'n_estimators'</span>]</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>best_n_estimators <span class="op">=</span> <span class="bu">int</span>(best_n_estimators)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>best_max_depth <span class="op">=</span> results_rf_df.sort_values(<span class="st">'rmse'</span>, ascending<span class="op">=</span><span class="va">True</span>).iloc[<span class="dv">0</span>][<span class="st">'max_depth'</span>]</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>best_max_depth <span class="op">=</span> <span class="bu">int</span>(best_max_depth)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>best_min_samples_split <span class="op">=</span> results_rf_df.sort_values(<span class="st">'rmse'</span>, ascending<span class="op">=</span><span class="va">True</span>).iloc[<span class="dv">0</span>][<span class="st">'min_samples_split'</span>]</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>best_min_samples_split <span class="op">=</span> <span class="bu">int</span>(best_min_samples_split)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="188">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>random_forest <span class="op">=</span> RandomForestRegressor(random_state<span class="op">=</span><span class="dv">371</span>, n_estimators<span class="op">=</span>best_n_estimators, max_depth<span class="op">=</span>best_max_depth, min_samples_split<span class="op">=</span>best_min_samples_split)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>random_forest.fit(train_features, train_labels)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>random_forest_pred <span class="op">=</span> random_forest.predict(test_features)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>random_forest_mse <span class="op">=</span> mean_squared_error(test_labels, random_forest_pred)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>random_forest_rmse <span class="op">=</span> np.sqrt(random_forest_mse)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Random Forest RMSE: '</span>, random_forest_rmse)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>random_forest_mae <span class="op">=</span> mean_absolute_error(test_labels, random_forest_pred)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Random Forest MAE: '</span>, random_forest_mae)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>random_forest_r2 <span class="op">=</span> r2_score(test_labels, random_forest_pred)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Random Forest R2: '</span>, random_forest_r2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest RMSE:  0.12227463208386215
Random Forest MAE:  0.056880422372448634
Random Forest R2:  0.006759822234491675</code></pre>
</div>
</div>
<div class="cell" data-execution_count="187">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib <span class="im">import</span> pyplot <span class="im">as</span> plt</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>plt.plot(test_features[<span class="st">'mjage'</span>], rand_pred, label<span class="op">=</span><span class="st">'Random Model'</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>plt.plot(test_features[<span class="st">'mjage'</span>], decision_tree_pred, label<span class="op">=</span><span class="st">'Decision Tree'</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>plt.plot(test_features[<span class="st">'mjage'</span>], random_forest_pred, label<span class="op">=</span><span class="st">'Random Forest'</span>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>plt.scatter(train_features[<span class="st">'mjage'</span>], train_labels, label<span class="op">=</span><span class="st">'Training Data'</span>, color<span class="op">=</span><span class="st">'k'</span>)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>plt.scatter(test_features[<span class="st">'mjage'</span>], test_labels, label<span class="op">=</span><span class="st">'Testing Data'</span>, color<span class="op">=</span><span class="st">'purple'</span>)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Age of First Marijuana Use'</span>)</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Probability of Severe Mental Illness'</span>)</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Decision Tree Regression'</span>)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="regression_files/figure-html/cell-19-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<table class="table">
<thead>
<tr class="header">
<th>Model</th>
<th>RMSE</th>
<th>MAE</th>
<th>R2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Random Baseline</td>
<td>0.5528</td>
<td>0.4730</td>
<td>-19.3003</td>
</tr>
<tr class="even">
<td>Decision Tree</td>
<td>0.1221</td>
<td>0.0566</td>
<td>0.0104</td>
</tr>
<tr class="odd">
<td>Random Forest</td>
<td>0.1221</td>
<td>0.0568</td>
<td>0.009</td>
</tr>
</tbody>
</table>
<p>We can see from our final results that the baseline model performed the worst of all the models. This is expected since the baseline model is just random predictions. The baseline model has a root mean squared error of 0.5528, a mean absolute error of 0.4730, and an R2 score of -19.3003. Since our outcome value is a probability, the root mean squared error and mean absolute error are both quite large, equally almost 50% of the outcome value. All these metrics indicate that the baseline model is not a good model.</p>
<p>The single decision tree model performs suprisingly well, netting a root mean squared error of 0.1221, a mean absolute error of 0.0566, and an R2 score of 0.0104. This is a significant improvement over the baseline model. The root mean squared error and mean absolute error are about a quarter of the size of those for the baseline model, indicating improved performance. These error values indicate that the decision tree model is a good model. However, the R2 score is very close to 0, indicating that the model is not very good at predicting the outcome. This is not surprising since decision trees are better at classification than regression.</p>
<p>Finally, we see that the random forest model performs about the same as the single decision tree model. The random forest model has a root mean squared error of 0.1221, a mean absolute error of 0.0568, and an R2 score of 0.009. The metrics for the random forest are actually slightly worse than those for the single decision tree. This is somewhat surprising since we tuned this model, but it is likely due to the fact that our data is not a strong predictor of the outcome.</p>
<p>Overall, we get a good model from the single decision tree. However, the random forest model does not improve on the single decision tree model. This is likely due to the fact that our data is not a strong predictor of the outcome. This indicates that in this dataset, cannabis usage is not a strong predictor of predicted probability of severe mental illness. This is a surprising result, since we expected cannabis usage to be a strong predictor of mental illness. However, part of this result may be due to the fact that we do not have direct mental illness data. Instead, we have a predicted probability of mental illness, which is a proxy for mental illness. This may be why our models do not perform as well as we expected.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Authored by Marion Geary Bauman, 2023</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mfgeary">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/marion-geary-bauman">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>