<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Sentiment Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../style.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">DSAN 5000: Cannabis and Psychosis</span>
    </a>
  </div>
          <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://mgb.georgetown.domains" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
</ul>
          <div class="quarto-navbar-tools ms-auto">
    <a href="https://github.com/mfgeary" rel="" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
    <a href="https://www.linkedin.com/in/marion-geary-bauman" rel="" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-linkedin"></i></a>
</div>
            <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../sentiment_analysis/sentiment_analysis.html">Sentiment Analysis</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About Marion</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://github.com/anly501/dsan-5000-project-mfgeary" class="sidebar-item-text sidebar-link"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text">Code</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://github.com/anly501/dsan-5000-project-mfgeary/tree/main/dsan-website/5000-website/data/raw_data" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Raw Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://github.com/anly501/dsan-5000-project-mfgeary/tree/main/dsan-website/5000-website/data" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Clean Data</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data-collection/data-collection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Gathering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data-cleaning/data-cleaning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Cleaning</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../eda/eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Exploration</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../naive-bayes/naive-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Naïve Bayes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../clustering/clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Clustering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../dim-reduction/dim-reduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dimensionality Reduction</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Decision Trees</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decision-tree/regression/regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../decision-tree/classification/classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Classification</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sentiment_analysis/sentiment_analysis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Sentiment Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../conclusions/conclusions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conclusions</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">Data Preparation</a></li>
  <li><a href="#sentiment-analysis" id="toc-sentiment-analysis" class="nav-link" data-scroll-target="#sentiment-analysis">Sentiment Analysis</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#chi-squared-test" id="toc-chi-squared-test" class="nav-link" data-scroll-target="#chi-squared-test">Chi-Squared Test</a></li>
  <li><a href="#pairwise-chi-squared-tests" id="toc-pairwise-chi-squared-tests" class="nav-link" data-scroll-target="#pairwise-chi-squared-tests">Pairwise Chi-Squared Tests</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Sentiment Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="overview" class="level1">
<h1>Overview</h1>
<p>One of our main data science questions relates to public opinion regarding cannabis and psychosis. Specifically, these three research questions remain unaddressed in previous sections of our research:</p>
<ul>
<li>What is the public sentiment regarding cannabis?</li>
<li>Does public sentiment indicate an awareness of the dangers of cannabis, especially as related to psychosis?</li>
<li>What is the public sentiment regarding cannabinoids such as CBD and THC products?</li>
</ul>
<p>To answer these questions, we will perform sentiment analysis on the three subreddits we have been analyzing: r/Psychosis, r/schizophrenia, and r/weed. In this analysis, our main goal is to first determine whether the post mentions cannabis, psychosis, or both. We will then use a language model to determine the attitude of the post towards cannabis and psychosis.</p>
</section>
<section id="data-preparation" class="level1">
<h1>Data Preparation</h1>
<p>Since we are using a language model, we will need to use our original dataset. In the cleaning process, we removed stopwords, numbers, and other non-essential words. However, in order for a language model to work well, we actually want to keep every word in the post. These words provide context for the language model to model the relationships between words in the text.</p>
<div class="cell" data-execution_count="5">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> json</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">"../../data/raw_data/reddit_psychosis_data.json"</span>) <span class="im">as</span> f:</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    reddit_psychosis <span class="op">=</span> json.load(f)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">'../../data/raw_data/reddit_cannabis_data.json'</span>) <span class="im">as</span> f:</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    reddit_cannabis <span class="op">=</span> json.load(f)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">"../../data/raw_data/reddit_schizophrenia_data.json"</span>) <span class="im">as</span> f:</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    reddit_schizophrenia <span class="op">=</span> json.load(f)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="6">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> parse_reddit_json(reddit_json):</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    text_list <span class="op">=</span> []</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    title_list <span class="op">=</span> []</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    subreddit_list <span class="op">=</span> []</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">100</span>):</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>        index <span class="op">=</span> <span class="bu">str</span>(i)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">100</span>):</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>            text_list.append(reddit_json[index][<span class="st">'data'</span>][<span class="st">'children'</span>][j][<span class="st">'data'</span>][<span class="st">'selftext'</span>])</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>            title_list.append(reddit_json[index][<span class="st">'data'</span>][<span class="st">'children'</span>][j][<span class="st">'data'</span>][<span class="st">'title'</span>])</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>            subreddit_list.append(reddit_json[index][<span class="st">'data'</span>][<span class="st">'children'</span>][j][<span class="st">'data'</span>][<span class="st">'subreddit'</span>])</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> text_list, title_list, subreddit_list</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>psy_text, psy_title, psy_sub <span class="op">=</span> parse_reddit_json(reddit_psychosis)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>schiz_text, schiz_title, schiz_sub <span class="op">=</span> parse_reddit_json(reddit_schizophrenia)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>cannabis_text, cannabis_title, cannabis_sub <span class="op">=</span> parse_reddit_json(reddit_cannabis)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>text <span class="op">=</span> psy_text <span class="op">+</span> schiz_text <span class="op">+</span> cannabis_text</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>title <span class="op">=</span> psy_title <span class="op">+</span> schiz_title <span class="op">+</span> cannabis_title</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>sub <span class="op">=</span> psy_sub <span class="op">+</span> schiz_sub <span class="op">+</span> cannabis_sub</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>reddit_df <span class="op">=</span> pd.DataFrame({<span class="st">'text'</span>: text, <span class="st">'title'</span>: title, <span class="st">'subreddit'</span>: sub})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="7">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>reddit_df[<span class="st">'full_text'</span>] <span class="op">=</span> reddit_df[<span class="st">'title'</span>] <span class="op">+</span> <span class="st">' '</span> <span class="op">+</span> reddit_df[<span class="st">'text'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="36">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>reddit_df.drop_duplicates(subset<span class="op">=</span><span class="st">'full_text'</span>, inplace<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now that we have our original dataset, we will need to create a new column that indicates whether the post mentions cannabis, psychosis, or both. We will use a list of keywords linked to cannabis and psychosis to determine whether the post mentions either of these topics. We will create a new column indicating whether each post mentions cannabis, psychosis, or both.</p>
<div class="cell" data-execution_count="37">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>cannabis_words <span class="op">=</span> [<span class="st">'cannabis'</span>, <span class="st">'weed'</span>, <span class="st">'marijuana'</span>, <span class="st">'420'</span>, <span class="st">'blunt'</span>, <span class="st">'joint'</span>, <span class="st">'high'</span>, <span class="st">'stoned'</span>, <span class="st">'smoke'</span>, <span class="st">'smoking'</span>, <span class="st">'😮‍💨'</span>]</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>schiz_words <span class="op">=</span> [<span class="st">'schizophrenia'</span>, <span class="st">'schizo'</span>, <span class="st">'schizoaffective'</span>, <span class="st">'schizotypal'</span>, <span class="st">'schizoid'</span>, <span class="st">'schiz'</span>, <span class="st">'hallucination'</span>, <span class="st">'delusion'</span>, <span class="st">'psychosis'</span>, <span class="st">'psychotic'</span>]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> label_subreddit_cannabis(text):</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> word <span class="kw">in</span> cannabis_words:</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> word <span class="kw">in</span> text:</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="va">True</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="va">False</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> label_subreddit_schiz(text):</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> word <span class="kw">in</span> schiz_words:</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> word <span class="kw">in</span> text:</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="va">True</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="va">False</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>reddit_df[<span class="st">'cannabis'</span>] <span class="op">=</span> reddit_df[<span class="st">'full_text'</span>].<span class="bu">apply</span>(label_subreddit_cannabis)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>reddit_df[<span class="st">'schiz'</span>] <span class="op">=</span> reddit_df[<span class="st">'full_text'</span>].<span class="bu">apply</span>(label_subreddit_schiz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="38">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> label_subreddit(text):</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> label_subreddit_cannabis(text) <span class="kw">and</span> label_subreddit_schiz(text):</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'both'</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> label_subreddit_schiz(text):</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'psychosis'</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> label_subreddit_cannabis(text):</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'cannabis'</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'neither'</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>reddit_df[<span class="st">'label'</span>] <span class="op">=</span> reddit_df[<span class="st">'full_text'</span>].<span class="bu">apply</span>(label_subreddit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="39">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(reddit_df[<span class="st">'label'</span>].value_counts())</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(reddit_df[<span class="st">'label'</span>].value_counts(normalize<span class="op">=</span><span class="va">True</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>label
neither      195
psychosis     61
cannabis      36
both           7
Name: count, dtype: int64
label
neither      0.652174
psychosis    0.204013
cannabis     0.120401
both         0.023411
Name: proportion, dtype: float64</code></pre>
</div>
</div>
<div class="cell" data-execution_count="40">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib <span class="im">import</span> pyplot <span class="im">as</span> plt</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>reddit_df[<span class="st">'label'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Distribution of Reddit Text Labels'</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Label'</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Reddit Posts'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="40">
<pre><code>Text(0, 0.5, 'Number of Reddit Posts')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="sentiment_analysis_files/figure-html/cell-9-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="41">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>reddit_df[reddit_df[<span class="st">'label'</span>] <span class="op">==</span> <span class="st">'both'</span>][[<span class="st">'full_text'</span>, <span class="st">'label'</span>]].head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="41">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">full_text</th>
<th data-quarto-table-cell-role="th">label</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">21</td>
<td>NEVER smoke weed if you experience psychosis I...</td>
<td>both</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">33</td>
<td>My little brother jumped of the 12th floor dur...</td>
<td>both</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">53</td>
<td>I had chronic psychosis for over 7 months and ...</td>
<td>both</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">55</td>
<td>Weed can be dangerous too guys Went to have a ...</td>
<td>both</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">69</td>
<td>I ruined my entire life and I’m only 23 I don’...</td>
<td>both</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">93</td>
<td>I stabbed my friend in Psychosis Already spent...</td>
<td>both</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10053</td>
<td>Schizophrenics labeled “Karens” I keep seeing ...</td>
<td>both</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>We see that the majority of posts (65%) do not mention cannabis or psychosis. On the other end of the spectrum, 2% of posts mention both cannabis and psychosis. The remaining 33% of posts mention either cannabis or psychosis, with psychosis being mentioned more often than cannabis.</p>
</section>
<section id="sentiment-analysis" class="level1">
<h1>Sentiment Analysis</h1>
<p>Now that we have labeled data, we want to perform sentiment analysis on the text. We are specifically interested in the sentiment of text that mentions both cannabis and psychosis, but we will analyze all the text data because samples that mention both are very limited.</p>
<p>To perform sentiment analysis, we will use the <code>txtai</code> library. We use <code>sentence-transformers/nli-mpnet-base-v2</code>, a high-quality, open source model for our sentence embeddings. Then, we use <code>distilbert-base-uncased-finetuned-sst-2-english</code> to perform sentiment analysis on the sentence embeddings. Both of these models are pre-trained on large datasets, so we can use transfer learning to apply them to our data. They are relatively light-weight and have high accuracy, so they are ideal for our purposes.</p>
<div class="cell" data-execution_count="47">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> transformers <span class="im">import</span> pipeline</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> txtai.embeddings <span class="im">import</span> Embeddings</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>sentiment_analyzer <span class="op">=</span> pipeline(<span class="st">"sentiment-analysis"</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>embeddings <span class="op">=</span> Embeddings(path<span class="op">=</span><span class="st">"sentence-transformers/nli-mpnet-base-v2"</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>text <span class="op">=</span> <span class="st">"I love using txtai for natural language processing!"</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>sentiment_result <span class="op">=</span> sentiment_analyzer(text)[<span class="dv">0</span>]</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sentiment: </span><span class="sc">{</span>sentiment_result[<span class="st">'label'</span>]<span class="sc">}</span><span class="ss"> (confidence: </span><span class="sc">{</span>sentiment_result[<span class="st">'score'</span>]<span class="sc">:.2f}</span><span class="ss">)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Sentiment: POSITIVE (confidence: 1.00)</code></pre>
</div>
</div>
<div class="cell" data-execution_count="49">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> index, row <span class="kw">in</span> reddit_df.iterrows():</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    text <span class="op">=</span> row[<span class="st">'full_text'</span>]</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">len</span>(text) <span class="op">&gt;</span> <span class="dv">512</span>:</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>        text <span class="op">=</span> text[:<span class="dv">512</span>]</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Get the sentiment for the text</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    sentiment_result <span class="op">=</span> sentiment_analyzer(text)[<span class="dv">0</span>]</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    reddit_df.loc[index, <span class="st">'sentiment'</span>] <span class="op">=</span> sentiment_result[<span class="st">'label'</span>]</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    reddit_df.loc[index, <span class="st">'sentiment_confidence'</span>] <span class="op">=</span> sentiment_result[<span class="st">'score'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<div class="cell" data-execution_count="50">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>reddit_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="50">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">text</th>
<th data-quarto-table-cell-role="th">title</th>
<th data-quarto-table-cell-role="th">subreddit</th>
<th data-quarto-table-cell-role="th">full_text</th>
<th data-quarto-table-cell-role="th">cannabis</th>
<th data-quarto-table-cell-role="th">schiz</th>
<th data-quarto-table-cell-role="th">label</th>
<th data-quarto-table-cell-role="th">sentiment</th>
<th data-quarto-table-cell-role="th">sentiment_confidence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>3 years post-psychosis in recovery some days c...</td>
<td>first time smiling on camera in... 3 years!</td>
<td>Psychosis</td>
<td>first time smiling on camera in... 3 years! 3 ...</td>
<td>False</td>
<td>True</td>
<td>psychosis</td>
<td>POSITIVE</td>
<td>0.996600</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td></td>
<td>I quit my meds lmfao</td>
<td>Psychosis</td>
<td>I quit my meds lmfao</td>
<td>False</td>
<td>False</td>
<td>neither</td>
<td>NEGATIVE</td>
<td>0.999569</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td></td>
<td>I hate it here</td>
<td>Psychosis</td>
<td>I hate it here</td>
<td>False</td>
<td>False</td>
<td>neither</td>
<td>NEGATIVE</td>
<td>0.999582</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td></td>
<td>art by me. I thought it kinda visualized how I...</td>
<td>Psychosis</td>
<td>art by me. I thought it kinda visualized how I...</td>
<td>False</td>
<td>False</td>
<td>neither</td>
<td>POSITIVE</td>
<td>0.990578</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td></td>
<td>But I’m still god and this is neither a joke a...</td>
<td>Psychosis</td>
<td>But I’m still god and this is neither a joke a...</td>
<td>False</td>
<td>True</td>
<td>psychosis</td>
<td>POSITIVE</td>
<td>0.996085</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">20095</td>
<td></td>
<td>*sigh* Everything reminds me of her...</td>
<td>weed</td>
<td>*sigh* Everything reminds me of her...</td>
<td>False</td>
<td>False</td>
<td>neither</td>
<td>POSITIVE</td>
<td>0.999636</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">20096</td>
<td></td>
<td>r/nevertellmetheodds</td>
<td>weed</td>
<td>r/nevertellmetheodds</td>
<td>False</td>
<td>False</td>
<td>neither</td>
<td>NEGATIVE</td>
<td>0.950680</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">20097</td>
<td></td>
<td>I smoked weed in her basement 😮‍💨</td>
<td>weed</td>
<td>I smoked weed in her basement 😮‍💨</td>
<td>True</td>
<td>False</td>
<td>cannabis</td>
<td>NEGATIVE</td>
<td>0.995856</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">20098</td>
<td></td>
<td>smoke what?</td>
<td>weed</td>
<td>smoke what?</td>
<td>True</td>
<td>False</td>
<td>cannabis</td>
<td>NEGATIVE</td>
<td>0.993274</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">20099</td>
<td></td>
<td>I handle things better being delusional 😅</td>
<td>weed</td>
<td>I handle things better being delusional 😅</td>
<td>False</td>
<td>True</td>
<td>psychosis</td>
<td>NEGATIVE</td>
<td>0.995858</td>
</tr>
</tbody>
</table>

<p>299 rows × 9 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="52">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>reddit_df[<span class="st">'sentiment'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Distribution of Reddit Text Sentiment'</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Sentiment'</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Reddit Posts'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="52">
<pre><code>Text(0, 0.5, 'Number of Reddit Posts')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="sentiment_analysis_files/figure-html/cell-14-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="53">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>reddit_df[<span class="st">'sentiment_confidence'</span>].plot(kind<span class="op">=</span><span class="st">'hist'</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Distribution of Reddit Text Sentiment Confidence'</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Sentiment Confidence'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="53">
<pre><code>Text(0.5, 0, 'Sentiment Confidence')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="sentiment_analysis_files/figure-html/cell-15-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="58">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the distribution of sentiment confidence for each sentiment</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>reddit_df[reddit_df[<span class="st">'sentiment'</span>] <span class="op">==</span> <span class="st">'NEGATIVE'</span>][<span class="st">'sentiment_confidence'</span>].plot(kind<span class="op">=</span><span class="st">'hist'</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>reddit_df[reddit_df[<span class="st">'sentiment'</span>] <span class="op">==</span> <span class="st">'POSITIVE'</span>][<span class="st">'sentiment_confidence'</span>].plot(kind<span class="op">=</span><span class="st">'hist'</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Distribution of Reddit Text Sentiment Confidence'</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Sentiment Confidence'</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>plt.legend([<span class="st">'Negative'</span>, <span class="st">'Positive'</span>])</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="sentiment_analysis_files/figure-html/cell-16-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="65">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>fig, axs <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>))</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">0</span>, <span class="dv">0</span>].set_title(<span class="st">'Neither'</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>reddit_df[reddit_df[<span class="st">'label'</span>] <span class="op">==</span> <span class="st">'neither'</span>][<span class="st">'sentiment'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>, ax<span class="op">=</span>axs[<span class="dv">0</span>, <span class="dv">0</span>])</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">0</span>, <span class="dv">1</span>].set_title(<span class="st">'Cannabis'</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>reddit_df[reddit_df[<span class="st">'label'</span>] <span class="op">==</span> <span class="st">'cannabis'</span>][<span class="st">'sentiment'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>, ax<span class="op">=</span>axs[<span class="dv">0</span>, <span class="dv">1</span>])</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">1</span>, <span class="dv">0</span>].set_title(<span class="st">'Psychosis'</span>)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>reddit_df[reddit_df[<span class="st">'label'</span>] <span class="op">==</span> <span class="st">'psychosis'</span>][<span class="st">'sentiment'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>, ax<span class="op">=</span>axs[<span class="dv">1</span>, <span class="dv">0</span>])</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">1</span>, <span class="dv">1</span>].set_title(<span class="st">'Both'</span>)</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>reddit_df[reddit_df[<span class="st">'label'</span>] <span class="op">==</span> <span class="st">'both'</span>][<span class="st">'sentiment'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>, ax<span class="op">=</span>axs[<span class="dv">1</span>, <span class="dv">1</span>])</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">'Distribution of Reddit Text Sentiment by Label'</span>)</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="sentiment_analysis_files/figure-html/cell-17-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Through visualization, it appears that the sentiment of text is more negative for posts that mention psychosis and/or cannabis than for posts that do not. It also appears that the sentiment of text is more negative for posts that mention cannabis than for posts that mention psychosis. In order to test these hypotheses, we will perform a chi-squared tests.</p>
<section id="chi-squared-test" class="level2">
<h2 class="anchored" data-anchor-id="chi-squared-test">Chi-Squared Test</h2>
<div class="cell" data-execution_count="105">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># chi squared test</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> chi2_contingency</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> chi2</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>contingency_table <span class="op">=</span> pd.crosstab(reddit_df[<span class="st">'label'</span>], reddit_df[<span class="st">'sentiment'</span>])</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Observed values:</span><span class="ch">\n</span><span class="st">-----------------"</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(contingency_table)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>stat, p, dof, expected <span class="op">=</span> chi2_contingency(contingency_table)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Expected values:</span><span class="ch">\n</span><span class="st">-----------------"</span>)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>contingency_table_obs <span class="op">=</span> pd.DataFrame(expected, index<span class="op">=</span>contingency_table.index, columns<span class="op">=</span>contingency_table.columns)</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(contingency_table_obs)</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Chi-squared statistic: </span><span class="sc">{</span>stat<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p-value: </span><span class="sc">{</span>p<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Observed values:
-----------------
sentiment  NEGATIVE  POSITIVE
label                        
both              5         2
cannabis         30         6
neither          97        98
psychosis        39        22

Expected values:
-----------------
sentiment    NEGATIVE   POSITIVE
label                           
both         4.003344   2.996656
cannabis    20.588629  15.411371
neither    111.521739  83.478261
psychosis   34.886288  26.113712

Chi-squared statistic: 16.179221113176837
p-value: 0.0010419638850492738</code></pre>
</div>
</div>
<p>From our chi-squared text, we get a p-value of 0.001. This indicates that we have strong evidence to suggest that the sentiment of text is different for posts with different labels. Next, I would like to perform pairwise chi-squared tests to determine which labels are different from each other. This will help me analyze the difference between each label.</p>
</section>
<section id="pairwise-chi-squared-tests" class="level2">
<h2 class="anchored" data-anchor-id="pairwise-chi-squared-tests">Pairwise Chi-Squared Tests</h2>
<div class="cell" data-execution_count="104">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>contingency_table.index</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="104">
<pre><code>Index(['neither', 'psychosis'], dtype='object', name='label')</code></pre>
</div>
</div>
<div class="cell" data-execution_count="108">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pairwise chi squared tests</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> itertools <span class="im">import</span> combinations</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label1, label2 <span class="kw">in</span> combinations(contingency_table.index, <span class="dv">2</span>):</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    contingency_table_new <span class="op">=</span> pd.crosstab(reddit_df[reddit_df[<span class="st">'label'</span>].isin([label1, label2])][<span class="st">'label'</span>], reddit_df[reddit_df[<span class="st">'label'</span>].isin([label1, label2])][<span class="st">'sentiment'</span>])</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    stat, p, dof, expected <span class="op">=</span> chi2_contingency(contingency_table_new)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Chi-squared test for </span><span class="sc">{</span>label1<span class="sc">}</span><span class="ss"> and </span><span class="sc">{</span>label2<span class="sc">}</span><span class="ss">:"</span>)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"p-value: </span><span class="sc">{</span>p<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Chi-squared test for both and cannabis:
p-value: 0.8338

Chi-squared test for both and neither:
p-value: 0.4576

Chi-squared test for both and psychosis:
p-value: 1.0000

Chi-squared test for cannabis and neither:
p-value: 0.0004

Chi-squared test for cannabis and psychosis:
p-value: 0.0711

Chi-squared test for neither and psychosis:
p-value: 0.0732
</code></pre>
</div>
</div>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions</h2>
<p>By performing the pair-wise chi-squared test, we are able to compare each label to each other label. We see that there is no evidence of a difference in sentiment between posts that mention both cannabis and psychosis and any other type of post. This indicates that posts that discuss both cannabis and psychosis are not more negative than posts that discuss only one of these topics or neither of these topics.</p>
<p>There is some evidence to suggest that posts that mention cannabis are more negative than posts that mention psychosis. However, the p-value is 0.0711, so the evidence is not very strong. There is also some evidence to suggest that posts that mention neither cannabis nor psychosis are more negative than posts that mention psychosis. However, the p-value is 0.0732, which is again not very strong evidence. This aligns with our visualization, which shows that posts that mention psychosis seem to be a bit more positive than posts that mention neither cannabis or both cannabis and psychosis.</p>
<p>This is strong evidence to suggest that posts that mention cannabis are more negative than posts that mention neither cannabis nor psychosis. This aligns with our visualization, which shows that posts that mention cannabis are much more negative than posts that mention neither cannabis nor psychosis. This is an interesting result, as we would expect posts mentioning cannabis on a subreddit dedicated to cannabis usage to generally consider cannabis usage to be positive. Below we visualize the subreddit distribution of posts mentioning cannabis:</p>
<div class="cell" data-execution_count="117">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the sentiment and the subreddit label</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Use sentiment as the x axis and the subreddit as the hue</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Make a plot for each label</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>sns.countplot(x<span class="op">=</span><span class="st">'sentiment'</span>, hue<span class="op">=</span><span class="st">'subreddit'</span>, data<span class="op">=</span>reddit_df[reddit_df[<span class="st">'label'</span>] <span class="op">==</span> <span class="st">'cannabis'</span>])</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Distribution of Sentiment by Subreddit Label for Cannabis'</span>)</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/mariongeary/anaconda3/envs/dsan5800/lib/python3.9/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
/Users/mariongeary/anaconda3/envs/dsan5800/lib/python3.9/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
/Users/mariongeary/anaconda3/envs/dsan5800/lib/python3.9/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
/Users/mariongeary/anaconda3/envs/dsan5800/lib/python3.9/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="sentiment_analysis_files/figure-html/cell-21-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>From our visualization, we see that cannabis usage is mentioned on both the r/weed subreddit and the r/schizophrenia subreddit. However, while cannabis usage is mentioned in both positive and negative lights on r/weed, it is only mentioned in a negative light on r/schizophrenia. This is likely the reason why posts mentioning cannabis are more negative than posts mentioning neither cannabis nor psychosis.</p>
<div class="cell" data-execution_count="141">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>label_order <span class="op">=</span> [<span class="st">'both'</span>, <span class="st">'psychosis'</span>, <span class="st">'cannabis'</span>, <span class="st">'neither'</span>]</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>fig, axs <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">5</span>))</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>reddit_weed_plot <span class="op">=</span> reddit_df[reddit_df[<span class="st">'subreddit'</span>] <span class="op">==</span> <span class="st">"weed"</span>].groupby([<span class="st">'label'</span>, <span class="st">'sentiment'</span>]).size().reset_index().pivot(columns<span class="op">=</span><span class="st">'label'</span>, index<span class="op">=</span><span class="st">'sentiment'</span>, values<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>reddit_weed_plot.plot(kind<span class="op">=</span><span class="st">'bar'</span>, stacked<span class="op">=</span><span class="va">True</span>, ax <span class="op">=</span> axs[<span class="dv">0</span>])</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">0</span>].set_title(<span class="st">'Distribution of Sentiment by r/weed'</span>)</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>reddit_schizophrenia_plot <span class="op">=</span> reddit_df[reddit_df[<span class="st">'subreddit'</span>] <span class="op">==</span> <span class="st">"schizophrenia"</span>].groupby([<span class="st">'label'</span>, <span class="st">'sentiment'</span>]).size().reset_index().pivot(columns<span class="op">=</span><span class="st">'label'</span>, index<span class="op">=</span><span class="st">'sentiment'</span>, values<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>reddit_schizophrenia_plot.plot(kind<span class="op">=</span><span class="st">'bar'</span>, stacked<span class="op">=</span><span class="va">True</span>, ax <span class="op">=</span> axs[<span class="dv">1</span>])</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">1</span>].set_title(<span class="st">'Distribution of Sentiment by r/schizophrenia'</span>)</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>reddit_psychosis_plot <span class="op">=</span> reddit_df[reddit_df[<span class="st">'subreddit'</span>] <span class="op">==</span> <span class="st">"Psychosis"</span>].groupby([<span class="st">'label'</span>, <span class="st">'sentiment'</span>]).size().reset_index().pivot(columns<span class="op">=</span><span class="st">'label'</span>, index<span class="op">=</span><span class="st">'sentiment'</span>, values<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>reddit_psychosis_plot.plot(kind<span class="op">=</span><span class="st">'bar'</span>, stacked<span class="op">=</span><span class="va">True</span>, ax <span class="op">=</span> axs[<span class="dv">2</span>])</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">2</span>].set_title(<span class="st">'Distribution of Sentiment by r/Psychosis'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="141">
<pre><code>Text(0.5, 1.0, 'Distribution of Sentiment by r/Psychosis')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="sentiment_analysis_files/figure-html/cell-22-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="126">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>contingency_table_sub <span class="op">=</span> pd.crosstab(reddit_df[<span class="st">'subreddit'</span>], reddit_df[<span class="st">'sentiment'</span>])</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Observed values:</span><span class="ch">\n</span><span class="st">-----------------"</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(contingency_table_sub)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>stat, p, dof, expected <span class="op">=</span> chi2_contingency(contingency_table_sub)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Expected values:</span><span class="ch">\n</span><span class="st">-----------------"</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>contingency_table_sub_obs <span class="op">=</span> pd.DataFrame(expected, index<span class="op">=</span>contingency_table_sub.index, columns<span class="op">=</span>contingency_table_sub.columns)</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(contingency_table_sub_obs)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Chi-squared statistic: </span><span class="sc">{</span>stat<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p-value: </span><span class="sc">{</span>p<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Observed values:
-----------------
sentiment      NEGATIVE  POSITIVE
subreddit                        
Psychosis            53        47
schizophrenia        55        44
weed                 63        37

Expected values:
-----------------
sentiment       NEGATIVE   POSITIVE
subreddit                          
Psychosis      57.190635  42.809365
schizophrenia  56.618729  42.381271
weed           57.190635  42.809365

Chi-squared statistic: 2.2038560956790123
p-value: 0.33222991062911966</code></pre>
</div>
</div>
<p>Based on this analysis, we see that there is not significant difference in sentiment between the different subreddits. This supports our evidence that the contents of the posts is a bigger indicator of sentiment irrespective of the subreddit.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>We see that posts mentioning cannabis are more negative than posts mentioning neither cannabis nor psychosis. This is likely due to the fact that cannabis is mentioned in a negative light on the r/schizophrenia subreddit. We also see that posts mentioning psychosis are more positive than posts mentioning neither cannabis nor psychosis. This is likely due to the fact that psychosis is mentioned in a positive light on the r/schizophrenia subreddit. Visually, we see that r/weed tends to have a more negative sentiment that the other two subreddits, but there is not strong statistical evidence to support this claim.</p>
<p>This analysis brings insight into our questions about sentiment regarding cannabis usage and psychosis. First, we see that cannabis usage is seen in a more negative light, even in spaces that we would expect to support cannabis usage, like r/weed. Next, we observe that there is some evidence to show that posts mentioning psychosis are actually more positive than those not mentioning psychosis, which is somewhat surprising. This is likely because r/Psychosis and r/schizophrenia are encouraging spaces meant to support those suffering from psychosis and working towards recovery. Finally, we see that posts mentioning both cannabis and psychosis are not more negative than other posts. There are also very few posts that mention both cannabis and psychosis. These may indicate that the public is not aware of the link between cannabis and psychosis, which aligns with my hypothesis. However, we cannot make any strong conclusions about this because there are so few posts that mention both cannabis and psychosis.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Authored by Marion Geary Bauman, 2023</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mfgeary">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/marion-geary-bauman">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>